### ISSUE TITLE
You missed a very important part of protocolVersion handshake.

### ISSUE THREAD

**Issue by M0nsterCat** [rfbproto/rfbproto#12]
"Handshaking begins by the server sending the client a ProtocolVersion message.  This lets the client know which is the highest RFB protocol version number supported by the server.  The client then replies with a similar message giving the version number of the protocol that should actually be used." - from official documentation. I was amazed when saw that client sends me 'R' instead of 1 for protocolVersion. You should include this: "The client then replies with a similar message giving the version number of the protocol that should actually be used." to your documentation.

**Comment by CendioOssman** [comment]
I'm afraid I don't understand what it is you wish to change. The sentence you suggest is already in the document.

**Comment by M0nsterCat** [comment]
Heh, yes, I missed it, sorry)
