### ISSUE TITLE
Encrypte the challenge giving by the server

### ISSUE THREAD

**Issue by Barbeblanche** [rfbproto/rfbproto#13]
Hi ! i want to reproduce a websockify connexion between client and noVNC server, using JMeter.
At the time of authentication, the server send a random 16 bytes challenge, but i can't encrypt this challenge using the password as key.

**Comment by CendioOssman** [comment]
The details should be clearly listed in the spec. Have you checked that you follow all details? E.g. the part with the bit order is a common issue. And have you compared your code with existing open source clients?

**Comment by Barbeblanche** [comment]
It was just the bit order issue. Thanks ! :)
