### ISSUE TITLE
Tight encoding - FillCompression paragraph is unclear

### ISSUE THREAD

**Issue by willbprog127** [rfbproto/rfbproto#19]
In this section
https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#tight-encoding

in this paragraph
>FillCompression 
>If the compression type is FillCompression, then the only pixel value follows, in TPIXEL format. This value applies to all pixels of the rectangle.

The wording here is unclear.  What is meant by '**the only pixel value** follows'  and 'This value applies to all pixels in the rectangle'?  What value are we talking about?

Here is the context:
> The Tight encoding makes use of a new type ``TPIXEL`` (Tight pixel).
This is the same as a ``PIXEL`` for the agreed pixel format, except
where *true-colour-flag* is non-zero, *bits-per-pixel* is 32, *depth*
is 24 and all of the bits making up the red, green and blue intensities
are exactly 8 bits wide. In this case a ``TPIXEL`` is only 3 bytes
long, where the first byte is the red component, the second byte is the
green component, and the third byte is the blue component of the pixel
color value.

> The data following the *compression-control* byte depends on the
compression method.

> **FillCompression**
>    If the compression type is **FillCompression**, then the only pixel
    value follows, in ``TPIXEL`` format. This value applies to all
    pixels of the rectangle.

The explanation makes it sound like just *one* pixel is being sent, but then it says that it applies to all pixels in the rectangle.  Can this part be reworded to actually make sense?  I'm confused by this and cannot continue with my project until I better understand what is being said here.

Thanks! :+1:

**Comment by CendioOssman** [comment]
You seem to have understood it correctly, in that a single pixel is sent. So I'm afraid you'll have to elaborate on where things go wrong. A rectangle is the basic graphical unit in RFB, and is described in the "Display protocol" section and "FramebufferUpdate".

**Comment by kenzierocks** [comment]
My understanding is that a single pixel value is sent. All pixels in the rectangle are to be set to that pixel value, hence the name "fill", since it works like the fill tool in graphics design.

**Comment by willbprog127** [comment]
@CendioOssman @kenzierocks Thank you for the explanation.  It does make sense now.  Sorry for the noise.
