### ISSUE TITLE
Conflicting information regarding reporting continuous update support

### ISSUE THREAD

**Issue by samhed** [rfbproto/rfbproto#20]
[This section](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#enablecontinuousupdates) says:

> Note that there is currently no way to determine if the server supports this message except for using the Tight Security Type authentication.

And [this section](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#7716continuousupdates-pseudo-encoding) says: 

> The server must send a EndOfContinuousUpdates message the first time it sees a SetEncodings message with the ContinuousUpdates pseudo-encoding, in order to inform the client that the extension is supported.

In my mind, that is contradictory

**Comment by CendioOssman** [comment]
Right, this should have been fixed in ae847c3791c6391680cae78a6ddad3fa553ee28a.

**Comment by CendioOssman** [comment]
Fixed in b33d8a9.

**Comment by samhed** [comment]
Thanks
