### ISSUE TITLE
Server/Client Fence not clear

### ISSUE THREAD

**Issue by hauketoenjes** [rfbproto/rfbproto#21]
Hello,

because i am implementing the rfb protocol at the moment, i wonder how the fences work exactly.

My  question is if it is normal that you receive more fences than frame buffer updates or am i just responding the wrong way. As i understand the fences, the server sends one and the client responds to it with the request flag cleared and any others it does not understand. Since i am using queues in my project i should understand all 3 (BlockAfter, BlockBefore and SyncNext?)?

So i am responding with the request bit clear and all the other bits remaining the same. 
The thing is now, that i am receiving so many of these fences, that i think i missunderstand how the exactly work. I would appreciate it, if anyone could clear that out or explain it.

It could possibly be a server side thing (I am using TigerVnc) but i want to be sure that i understand them the right way before i ask someone over there.

**Comment by CendioOssman** [comment]
It sounds like you've understood things correctly. And yes, TigerVNC sends a lot of fences. It uses them to monitor the client and make sure it isn't flodding it (or the network) with data.
