### ISSUE TITLE
Is ClientRedirect an official pseudo-encoding?

### ISSUE THREAD

**Issue by dcommander** [rfbproto/rfbproto#24]
My understanding from Brian H. is that the ClientRedirect pseudo-encoding and the "*Ident" VeNCrypt security types (which are only supported in the Java TigerVNC Viewer) were created for an internal portal and were never officially registered.  I had to disable ClientRedirect in my viewer because the -311 pseudo-encoding is used for something else in RealVNC (https://catonmat.net/ftp/rfbproto.pdf), and enabling it broke compatibility with recent RealVNC servers.  I would suggest removing the ClientRedirect entry in this protocol document until/unless it is officially registered.

**Comment by ossman** [comment]
-311 **is** officially registered for ClientRedirect:

https://www.iana.org/assignments/rfb/rfb.xml

The document you linked to lists CursorWithAlpha on -311, but the IANA registration for that is -314. I've also verified that RealVNC uses -314 when implementing that encoding in TigerVNC.

I wonder if they are using both -311 and -314...

So a bug in RealVNC that should be reported to them? Which version(s) did you see this on?

**Comment by dcommander** [comment]
I was a while ago, so maybe they have since fixed it, but I haven't re-tested.  Glad to know it's official now.  :)  But is the Ident VeNCrypt type also official?  I didn't see that mentioned in this document or in other VeNCrypt documentation.

**Comment by CendioOssman** [comment]
They were using -314 back in early 2017 when I wrote the cursor documentation (9f455e172e64ee5904e9e5628e7224d91593aed7). I did not check for any issues with -311 though as TigerVNC's native viewer does not support that.

I don't suppose you have a current RealVNC server up for a quick test? Or you, @bphinz?

As for VeNCrypt, I'm not sure there is an officially stated documentation so here is probably your best bet. Which implementations support Ident? Could someone be convinced to submit a patch here?

**Comment by bphinz** [comment]
I can't find a mailing list archive URL, but I sent this patch to the tigervnc-rfbproto DL on May 28, 2011.  I registered -311 in April 2011, and I notified RealVNC prior to that and they were the ones that directed me to go through IANA.

```
--- rfbproto.vencrypt3.rst	2011-05-28 13:32:58.577133148 -0400
+++ rfbproto.ident.rst	2011-05-28 13:32:09.229133118 -0400
@@ -663,6 +663,9 @@
 262             X509Plain       X509 encryption with Plain authentication
 263             TLSSASL         TLS encryption with SASL authentication
 264             X509SASL        X509 encryption with SASL authentication
+265             Ident           Ident authentication
+266             TLSIdent        TLS encryption with Ident authentication
+267             X509Ident       X509 encryption with Ident authentication
 =============== =============== =======================================
 
 After that client selects one VeNCrypt subtype sends back number of that
@@ -735,12 +738,33 @@
 After that server verifies if supplied credentials are correct and
 continues with the `SecurityResult`_ message.
 
+Ident subtype
+~~~~~~~~~~~~~
+
+Client sends the username in the following form:
+
+=============== ============= =========================================
+No. of bytes    Type          Description
+=============== ============= =========================================
+4               ``U32``       Username length
+Username length ``U8`` array  Username
+=============== ============= =========================================
+
+After that server verifies if supplied credentials are correct and
+continues with the `SecurityResult`_ message.
+
 Subtypes with Plain suffix
 ~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 Authentication continues with the `Plain subtype`_ method when TLS handshake
 is completed.
 
+Subtypes with Ident suffix
+~~~~~~~~~~~~~~~~~~~~~~~~~~
+
+Authentication continues with the `Ident subtype`_ method when TLS handshake
+is completed.
+
 Subtypes with SASL suffix
 ~~~~~~~~~~~~~~~~~~~~~~~~~
 
```

**Comment by CendioOssman** [comment]
I see that it unfortunately got lost in a thread. Do you think you could do a PR?

**Comment by bphinz** [comment]
PR submitted

**Comment by CendioOssman** [comment]
Great. I think that should cover everything here.
