### ISSUE TITLE
Unclear description wrt support multi-head support clients

### ISSUE THREAD

**Issue by berrange** [rfbproto/rfbproto#28]
I'm trying to understand how to support dynamic client initiated desktop resize, without also supporting multi-head configuration. 

The ExtendedDesktopSize message should support this use case but some parts of the description are not entirely clear to me.

AFAICT, conceptually in multi-head mode, the server has a single huge framebuffer that is sub-divided into multiple non-overlapping regions. After cutting out the individual regions for individual heads, there may remain some unused gaps, as different sized heads can't be tiled precisely gapless.  We would benefit from describing this a bit more explicitly I think.

For a traditional client, all heads will thus be merged together into a single huge view, and they'll still get "DesktopSize" encoding FramebufferUpdate messages when multi-head config changes, and so everything just works normally.

For a client which supports ExtendedDesktopSize, the FramebufferUpdate message, the x, y co-ordinates can be used to determine which head the update corresponds to.  They will only get "ExtendedDesktopSize" encoding in FramebufferUpdate messages, never a "DesktopSize" encoding.

When gets fuzzy is the scenario where a client supports ExtendedDesktopSize but does not want to implement multi head.

In this section:

https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#extendeddesktopsize-pseudo-encoding

> Note that a simple client which does not support multi head does not need to parse the list of screens and can simply display the entire framebuffer.

The problem with this recommendation is that AFAICT, there is no way for the client to figure out the dimensions of the entire framebuffer.  Such a client won't get the "DesktopSize" encoding FramebufferUpdate messages, so the only way to determine the entire framebuffer size is indeed to parse the list of screens and calculate their cumulative dimensions.  

What am I missing here ?  It seems this quoted sentence is simply wrong and needs rewriting to tell clients to calculate the union of dimensions of each screen.

**Comment by CendioOssman** [comment]
There is just a single ExtendedDesktopSize message sent per change, no matter how many monitors. The top left coordinate is always 0,0, so x and y are used for various status codes. The entire framebuffer is specified by width and height, so a simple client can just look at that. There is no need to join together each monitor details.

This mimics how things work on at least X11, in that from a graphics API point of view there is just this big square area of pixels. Checking which areas are actually displayed by a monitor is an extra hint that applications need to explicitly look for.

The spec currently states:

> The `width` and `height` indicates the new width and height of the framebuffer.

I was hoping that was clear, but evidently not. So I'm open to suggests on how to improve things.

**Comment by berrange** [comment]
Oh right, yes, I see what you mean.  I think can solve this by just having a bit more descriptive text about the concept of the unified framebuffer vs regions for individual heads. I'll see about proposing a doc update for review
