### ISSUE TITLE
Is a depth of 32 bits legal?

### ISSUE THREAD

**Issue by MarcusWichelmann** [rfbproto/rfbproto#38]
Hi,

while testing my [vnc-client library](https://github.com/MarcusWichelmann/MarcusW.VncClient) with several different server implementations, I noticed, that, in some scenarios, the UltraVNC server advertises a pixel format with 32bpp and a depth of 32 in its `ServerInit` message. I'm not sure, if the protocol allows this.

I interpret
> Bits-per-pixel is the number of bits used for each pixel value on the wire. This must be greater than or equal to the depth which is the number of useful bits in the pixel value.

as if the depth value must only be as large as the number of bits that are actually used to transmit the red, green and blue color information. Additional 8 bits, likely for alpha, are not "useful" in my understanding, because the RFB pixel format does not say anything about what these bits are for?

I can imagine two ways of handling this special case:
1. Servers advertising a depth of 32 bits are buggy and my client application should just throw an error. Also my client could try to request a different, "correct" pixel format with 24 bit depth to handle this case more gracefully.
2. A 32 bit depth is legal and my client should be able to work with it. In this case the bit-saving optimizations for `CPIXEL`s and `TPIXEL`s are of course not possible and every pixel will instead be 4 bytes on the wire when using `ZRLE`/`Tight`.

Maybe the protocol specification could be clarified in this regard?

Thank you for writing this document by the way, it was a **great** help!

Marcus

**Comment by octylFractal** [comment]
I might be a little rusty, but here's my reading of the spec.

The sentence right after the ones you quoted makes it clear that 32 is legal, and 24 is _not_:
> Currently bits-per-pixel must be 8, 16 or 32.

> I interpret [...] as if the depth value must only be as large as the number of bits that are actually used to transmit the red, green and blue color information.

I think this is incorrect. Perhaps you are confusing "bits-per-pixel" with the word "depth" in the spec's original sentence. Those are actually two separate values. The "bits-per-pixel" value that is sent on the wire must be "greater than or equal to" (>=) "the depth which is the number of useful bits in the pixel value." With a normal 8-bits-per-color format, "the depth" would be 24 bits, 3 colors times 8 bits. However, you can't actually _send_ 24, that's not allowed by the spec, so in "bits-per-pixel" you would send 32, despite only using 24 of those 32 bits.

> Additional 8 bits, likely for alpha, are not "useful" in my understanding, because the RFB pixel format does not say anything about what these bits are for?

32bpp does not mean that there is alpha, it can mean e.g. a 30-bit format with 2 unused bits, 10 bits for RGB. https://en.wikipedia.org/wiki/Color_depth#Deep_color_(30-bit)
Realistically an implementation can send _any_ combination of red/green/blue-max, and allocate those 32 bits however it pleases, see `PIXEL_FORMAT`'s definition [here](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#serverinit).

**Comment by MarcusWichelmann** [comment]
Thank you your your quick answer.

I was probably a bit unclear. Yeah, depth values like 30 bits are possible, of course, and my client can handle that, as long as these depth bits are actually allocated by the red, green and blue channels.

But in case of UltraVNC, the red/green/blue channels were 8 bits each and the **depth** was advertised as 32 bits. So there were 8 unallocated bits remaining. Please remember, I'm not talking about the bits per pixel here.

So my question is, if this is allowed according to the protocol implementation or if this is a bug in the server.

**Comment by octylFractal** [comment]
Okay, you did not specify originally that r/g/b were 8 each still. I think that sounds like a bug, though perhaps someone more familiar with the spec can give a stronger confirmation.

**Comment by CendioOssman** [comment]
Does indeed sound like a bug. Not clear if it is a violation of the specification though. It sure leaves some ambiguity on what to do with the bits not covered by red, green and blue.

Given that it's already in the wild it might be difficult to tighten things up now though. Is it causing any problems for you in your implementation?

For reference, TigerVNC will only complain if depth is too small, but not if it is too large:

https://github.com/TigerVNC/tigervnc/blob/2a0eabec3140c5bfbff83f2c68659259ab9cd34d/common/rfb/PixelFormat.cxx#L688


@rudidevos, any insight?

**Comment by MarcusWichelmann** [comment]
> Given that it's already in the wild it might be difficult to tighten things up now though. Is it causing any problems for you in your implementation?

Okay, then I probably should deal with it. Should only require me to change some sanity checks, my other code should support that already.

Oh, I just notice that you implemented a limit of max. 8 bits per channel. But the protocol does allow depths greater than that with e.g. 30 bits (10 bit per channel), as @octylFractal pointed out, right? My client code should theretically work with that, too, because the [generic path for the pixel conversions](https://github.com/MarcusWichelmann/MarcusW.VncClient/blob/master/src/MarcusW.VncClient/Protocol/Implementation/PixelConversions.cs#L95) operates on 32bit values when shifting things around anyway. Do you know any server implementation, that supports 30 bit deep color space, to test this?

**Comment by CendioOssman** [comment]
> Oh, I just notice that you implemented a limit of max. 8 bits per channel. But the protocol does allow depths greater than that with e.g. 30 bits (10 bit per channel), as @octylFractal pointed out, right?

Yeah, that's a TigerVNC limitation and not a protocol one. Might need to revisit that if HDR gets more traction.

> Do you know any server implementation, that supports 30 bit deep color space, to test this?

Nope.

**Comment by RudiDeVos** [comment]
When you set depth to 32, you just tell a pixel size is 32bit. This is a memory size, not a colorDepth
A framebuffer on most windows systems have 32Bit pixels, but use 24bit for colors.
A cpu is 32bit alligned, working with 32bit is just a lot fatser.

A 30bit color would also have a 32bit depth.  Only shift and Mask gonna differ from RGB.

**Comment by MarcusWichelmann** [comment]
I think you're mixing up "bits per pixel" and "depth" here, as it's used in the context of the protocol specification.

Yeah, working with 32bit is alright, and that's why "bits per pixel" is 32bpp in the RGB888/BGR888 case. But, then, the depth is only 24 bit, because only 24 bit are used for the red, green and blue color information, as you correctly said:

> A framebuffer on most windows systems have 32Bit pixels, but use 24bit for colors.

So the server should report 32 bits per pixel and a depth of 24. This is also, how it's intended by the `ZRLE` and `Tight` encodings because they then adapt the bits per pixel to the depth value of 24 to save some bytes on the wire (see `CPIXEL`/`TPIXEL`).

**Comment by RudiDeVos** [comment]
Is  the protocol changed ?
Original it was implemented like this (2002 AT&T vnc code.)
```
si.format.bitsPerPixel = (m_ScrUpdate.m_iBitsPerPixel == 24) ? 32 : m_ScrUpdate.m_iBitsPerPixel;
si.format.depth        = m_ScrUpdate.m_iBitsPerPixel;	/* 8 to 32 */
```

**Comment by MarcusWichelmann** [comment]
Eeeh, that looks strange to me. @CendioOssman ?

**Comment by CendioOssman** [comment]
I'm not sure where `m_iBitsPerPixel` comes from, so I can't really say much about that code. But I'd agree that "depth" commonly refers to the number of significant bits, and not any padding. But I can also concede that there are exceptions.

However in VNC's case there is both the "depth" and "bits per pixel" fields, so there must be some significant difference between them or one would just have sufficed.

VNC is largely based on X11 primitives, so these fields likely come from Pixmap formats in X11, where we also have those two fields. However it is similarly vague there and you have to look at X11 Visuals to get some idea of how bits are actually used.

And that is something we again see in VNC, that "depth" is largely meaningless in practice. It's the other fields that determine how colours are used.


So in the end there is little to be gained by being strict about depth. A too small depth suggests something has been decoded incorrectly, but a too large depth is just ambiguous with no real practical issues. And since it's already used that way I see no need to start considering it invalid.

**Comment by RudiDeVos** [comment]
`This is also, how it's intended by the ZRLE and Tight encodings because they then adapt the bits per pixel to the depth value of 24 to save some bytes on the wire (see CPIXEL/TPIXEL).`
If it's only used for the encoders changing it should not have a any impact.

I remember the only time i used is was with a 24bit video card.
As bbp doesn't allow 24 (rfb protocol) , it was passed as 32bpp en a depth of 24 for all other formats depth == bpp.

If TigerVNC implement it that way,  we can do the same.  If it break something for other... the need the change it.
Perhaps some remark in the protocol could make it clear.

**Comment by MarcusWichelmann** [comment]
@CendioOssman I agree and have changed my code now to be less strict.

> but a too large depth is just ambiguous with no real practical issues

Well yes, it won't cause issues, but one should at least keep in mind, that it might cause some inefficiencies in ZRLE and Tight.

From my side, it's all clear now and this issue can be closed. Thank you.

**Comment by RudiDeVos** [comment]
Yes, can be closed.  
I gonna try with setting it to 24.
If that fail,  zrle and Tight i gonna use the mask and shift to identify a real RGB (24). Then encoders should compress a little better... but also a little slower.  Perhaps i just add it has an extra encoder option.

**Comment by CendioOssman** [comment]
How about this clarification:

```rst
*Depth* should be the sum of bits used according to *red-max*,
*green-max*, and *blue-max*, or the number of bits needed for indices
in the colour map, depending on the value of *true-color-flag*. Note
that some servers will send a *depth* that is identical to
*bits-per-pixel* for historical reasons.
```

**Comment by RudiDeVos** [comment]
perfect

**Comment by MarcusWichelmann** [comment]
Yeah, that makes it more clear. :+1:

**Comment by CendioOssman** [comment]
Committed in d63560e39f4e1f150ce375cc59a24f6b3d921f96. :)
