### ISSUE TITLE
What does `first-color` means in `SetColorMapEntries`

### ISSUE THREAD

**Issue by vincenthcui** [rfbproto/rfbproto#42]
There is a 2 byte field named `first-color` in `SetColorMapEntries` messages, but I can't find any thing about what it is, or how it works. Nor

It will be very pleasure if anyone can tell. Thanks.

**Comment by CendioOssman** [comment]
A single message doesn't have to specify the entire colour map, and can instead update just a few entries. E.g. if I'd like to update entry 5 and 6 I'd specify `5` in `first-colour`, and `2` in `number-of-colours`, followed by two sets of RGB values.

Hope this makes things clearer.
