### ISSUE TITLE
RFB reference implementation

### ISSUE THREAD

**Issue by sgh** [rfbproto/rfbproto#56]
I'm implementing a simple implementation of the RFB protocol here. Much of it is done in the fastest most stupid way, but the main point is that it works quite well.

https://github.com/sgh/StupidVNC

The reason that I have done my own implementation is that libVNCServer has licensing restrictions making it forbidden to include in commercial products.

I would like you to link to my implementation int the hope that it can serve as a free LGPL reference implementation.

**Comment by any1** [comment]
That's neat. Are you aware of [Neat VNC](https://github.com/any1/neatvnc)?

**Comment by sgh** [comment]
No ... I search the entire web prior to spending the time. Do you know in which state that project is ?

**Comment by any1** [comment]
It's used by [wayvnc](https://github.com/any1/wayvnc) and [weston](https://gitlab.freedesktop.org/wayland/weston)

**Comment by CendioOssman** [comment]
There is already a history of many VNC implementations, and unfortunately some variation in how things have been implemented. So, I'm afraid it's a bit too late to bless any single implementation as the "reference" one. Any interoperability problems will need to be dealt with on a case-by-case basis, looking at what's most practical.

**Comment by sgh** [comment]
Makes sense :)
