### ISSUE TITLE
Pseudo-encoding for Tight basic compression with no zlib

### ISSUE THREAD

**Issue by dcommander** [rfbproto/rfbproto#59]
TurboVNC has been using an unofficial extension to Tight encoding since 2008, and I would like to go ahead and make it official.

The changes to **rfbproto.rst** would look something like this:

```
@@ -3098,14 +3098,16 @@ Bits            Binary value        Description
 =============== =================== ===================================
 
 Otherwise, if the bit 7 of *compression-control* is set to 1, then the
-compression method is either **FillCompression** or
-**JpegCompression**, depending on other bits of the same byte:
+compression method is either **FillCompression**, **JpegCompression**, or
+**BasicCompression** without zlib, depending on other bits of the same byte:
 
 =============== =================== ===================================
 Bits            Binary value        Description
 =============== =================== ===================================
 7-4             1000                **FillCompression**
 ..              1001                **JpegCompression**
+..              1010                **BasicCompression** without zlib
+..              1110                **BasicCompression** without zlib, *read-filter-id*
 ..              any other           Invalid
 =============== =================== ===================================
 
```

However, it would probably be best to use a new pseudo-encoding for this, since it isn't an original or required part of the Tight encoding spec.  (If the server attempts to use the extension and the viewer doesn't know how to handle it, then the viewer could crash with a zlib error if it tries to use Compression Level 0 with JPEG subencoding disabled.)

That leads me to the question of how one registers new pseudo-encodings these days.  vnc-list@realvnc.com appears to be kaput.

Assuming that a new pseudo-encoding can be obtained, I will submit a PR that breaks out the description into a new section similar to the current section for Tight + PNG.

**Comment by dcommander** [comment]
As far as why this extension exists, it's to support a Tight-based encoding method that minimizes CPU time, providing about 4-6x compression relative to Raw (almost as good of a compression ratio as Hextile) while using about half the CPU time of Hextile.  Its original purpose was to support older SPARC CPUs that couldn't keep up with JPEG or zlib decompression on a gigabit network.  However, it has found a new purpose both on loopback connections to virtual machines, as well as in enterprise environments that run a VNC viewer inside of Citrix or some other Windows remote desktop solution and want to minimize re-encoding overhead without completely blowing up the server-area network.

**Comment by CendioOssman** [comment]
> That leads me to the question of how one registers new pseudo-encodings these days. [vnc-list@realvnc.com](mailto:vnc-list@realvnc.com) appears to be kaput.

It is now handled by IANA:

https://www.iana.org/assignments/rfb/rfb.xml

You request numbers here:

https://www.iana.org/form/protocol-assignment

> As far as why this extension exists, it's to support a Tight-based encoding method that minimizes CPU time

I take it zlib at level 0 still does something that gives too much overhead?

**Comment by dcommander** [comment]
> I take it zlib at level 0 still does something that gives too much overhead?

Yeah, even with zlib-ng (which has SIMD acceleration and numerous other optimizations), disabling zlib altogether results in about a 10% speedup in average Tight encoding performance when using zlib level 0.  (When we use zlib level 0, we also forego JPEG, so most of the overhead is probably incurred with the Raw subencoding.)  Relative to the unaccelerated zlib implementation, the speedup is more like 60% for zlib 1.2.7 and 15% for zlib 1.2.11.  (I guess they optimized something in the more recent zlib releases.)  Since this mode is intended to minimize CPU usage, 10-15% matters.

I'm no zlib expert, but after looking at the code, I think the crux of the issue is that, even when you use level 0, it still continuously maintains the hash table and other stuff so that you can seamlessly switch back to higher zlib levels without having to wait for it to figure out the correct state.  The datastream with level 0 is the same as the datastream without zlib, except that it has interspersed headers that presumably depend on the state that is it continuously computing (presumably so the decoder can keep up with that state, even though it isn't technically decoding anything.)

**Comment by dcommander** [comment]
Pseudo-encoding requested from IANA.

**Comment by dcommander** [comment]
Created PR #64
