### ISSUE TITLE
VNC authentication section needs clarification

### ISSUE THREAD

**Issue by EnTerr** [rfbproto/rfbproto#6]
There is some important information missing on VNC auth - in particular that:
- only the first 8 characters of the key are to be used
- each key octet is to be bit-reversed first (e.g. \x20 -> \x04)
- DES is used in ECB mode (i.e. in 8-byte blocks, no chaining)

See http://bytecrafter.blogspot.com/2010/09/des-encryption-as-used-in-vnc.html
and http://www.vidarholen.net/contents/junk/vnc.html
which underline/explain that.

**Comment by willbprog127** [comment]
I wasted three days of work trying to get VNC authentication to work without knowing about the issues @EnTerr mentioned.  @EnTerr thanks for bringing this up!

Can you guys fix this sooner rather than later so others won't get caught in this trap? 😄 Thanks!

**Comment by CendioOssman** [comment]
Fixed in 8774cf7512b4a5fe52f8ab2093cd4534d2e6cb24.

**Comment by willbprog127** [comment]
@CendioOssman Thank you so much! :smile:
