### ISSUE TITLE
Tight Png encoding

### ISSUE THREAD

**Issue by vtolstov** [rfbproto/rfbproto#9]
This document miss Tight Png encoding description. If that possible - please add.

**Comment by qmfrederik** [comment]
I had a look into the Tight PNG encoding (for compatibility with noVNC). The documentation is a bit sparse. You can find additional information here:
* https://wiki.qemu.org/index.php/Features/VNC_Tight_PNG
* https://sourceforge.net/p/libvncserver/mailman/message/29200412/

In a nutshell, the Tight PNG encoding is the same as Tight encoding, with the addition of support for PNG encoding.

The server indicates a region is PNG-encoded by setting the upper bits of the *compression-control* byte to `1010`.

Bits | Binary value | Description
-- | -- | --
7-4 | 1000 | FillCompression
  | 1001 | JpegCompression
  | 1010 | PngCompression

When sending PNG-encoded data, the message format is exactly the same as when sending JPEG-encoded data in the Tight encoding, with the exception of the *compression-control* value set as above and the data being PNG-encoded.
